### ISSUE TITLE
Crash when won't find default URL

### ISSUE THREAD

**Issue by pvpfleczu** [jo3bingham/tibia-11-ip-changer#2]
When we don't have default URL in client.exe, then IP changer crash.

https://github.com/jo3bingham/tibia-11-ip-changer/blob/a4a9abbe75aa056f57458920cc1c6610a974b885/Tibia%2011%20IP%20Changer/Utilities/Constants.cs#L8

**Comment by jo3bingham** [comment]
Fixed: https://github.com/jo3bingham/tibia-11-ip-changer/pull/4
