### ISSUE TITLE
ScanString cannot ready rsaKey and loginServer

### ISSUE THREAD

**Issue by brunominervino** [jo3bingham/tibia-11-ip-changer#3]
Debug View:
![image](https://cloud.githubusercontent.com/assets/10432401/21464061/74167530-c95a-11e6-8adb-e5fe2b7f76ad.png)

I'm using the latest version of client:
![image](https://cloud.githubusercontent.com/assets/10432401/21464088/d1aec3a0-c95a-11e6-8259-f4c432bce89c.png)

**Comment by jo3bingham** [comment]
@macedot added a check to make sure the returned addresses aren't 0 in #4, however, I'll need to look in to why it's returning 0.
